public class ListViewButtonClass {

    /*public List<Le> opportunities{get;private set;}
    public ListViewButtonClass(ApexPages.StandardSetController stdSetController){
        // Returns all selected records
        opportunities = (List<Opportunity>) stdSetController.getSelected();
    }
    
    public PageReference save(){
        // Some fancy stuff here.
        try{
         update opportunities;
        } catch(Exception e){
            System.debug('Exception: ' + e);
        }
        return null;
    }*/
}